import './bootstrap';
import './modules/preloader';
import './modules/notification';
import './modules/mobile-menu';
import './modules/admin-sidebar';
import './modules/form-tracker';
import './modules/product-popup';
import './modules/slider';
import './modules/cart';